[package]
name = "black_scholes"
version = "0.2.4"
authors = ["Daniel Stahl <danstahl1138@gmail.com>"]
homepage = "https://github.com/phillyfan1138/black_scholes_rust"
repository = "https://github.com/phillyfan1138/black_scholes_rust"
readme = "README.md"
license = "MIT"
description = "A Black Scholes option pricing library."

[dependencies]
special = "0.7"
nrfind = "1.0.2"
[dev-dependencies]
approx = "0.2.0"

[badges]
travis-ci = { repository = "phillyfan1138/black_scholes_rust" }