name: RustDeploy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]

    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests stable
      if: matrix.rust == 'stable'
      run: cargo test --verbose
    - name: Document 
      run: cargo doc
    - name: Publish
      if: matrix.rust == 'stable'
      run: cargo publish --token ${{ secrets.CARGO_TOKEN }} --allow-dirty || true
