name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads
      run: cargo test --verbose
    - name: coverage
      run: |
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
        zip -0 ccov.zip `find . \( -name "black_scholes*.gc*" \) -print`
        ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info
        bash <(curl -s https://codecov.io/bash) -f lcov.info
    - name: Document
      run: cargo doc
    - name: Publish
      run: cargo publish --token ${{ secrets.CARGO_TOKEN }} --allow-dirty
